;; Compilation d'opérateurs de comparaison.

(defun compilation-comp (exp env fenv nomf)
  (let ((op (car exp))
	(fin (gensym "finTest")))
    (append (compilation (cadr exp) env fenv nomf)
	    '((PUSH :R0))           
	    (compilation (caddr exp) env fenv nomf)
	    '((PUSH :R0))
	    '((POP :R0))
	    '((POP :R1))
	    '((CMP :R1 :R0)) 
	    '((MOVE (:DIESE T) :R0)) 
	    (case op
	      ('= `((JEQ (@ ,fin))))
	      ('< `((JL (@ ,fin))))
	      ('> `((JG (@ ,fin))))
	      ('<= `((JLE (@ ,fin))))
	      ('>= `((JGE (@ ,fin))))
	      )
	    '((MOVE (:DIESE NIL) :R0))
	    `((@ ,fin)))
    )
  )

(defun compilation-and (exp etiqfin env fenv nomf)
  (if (null exp) 
      (append '((MOVE (:DIESE T) :R0)) `((@ ,etiqfin)))
    (append (compilation (car exp) env fenv nomf) 
	    '((CMP :R0 (:DIESE T)))
	    `((JNE (@ ,etiqfin)))
	    (compilation-and (cdr exp) etiqfin env fenv nomf))
    )
  )

(defun compilation-or (exp etiqfin env fenv nomf)
  (if (null exp) 
      (append '((MOVE (:DIESE NIL) :R0)) `((@ ,etiqfin)))
    (append (compilation (car exp) env fenv nomf)
	    '((CMP :R0 (:DIESE T)))
	    `((JEQ (@ ,etiqfin)))
	    (compilation-or (cdr exp) etiqfin env fenv nomf))
    )
  )